name: Release Knowlg Connector

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'  # Trigger only on tags like 1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Knowlg Connector Code
      uses: actions/checkout@v4

    - name: Set up Java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up Maven
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'

    - name: Build Knowlg Connector
      run: mvn clean package -DskipTests

    - name: Inspect target/ directory
      run: ls -lh target/

    - name: Rename distribution tarball
      run: |
        VERSION=${GITHUB_REF_NAME}
        echo "Detected version: $VERSION"
        cp target/sb-knowlg-connector-${VERSION}-distribution.tar.gz knowlg-connector.tar.gz

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: knowlg-connector.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}